title: Concise
description: A simple and concise Jekyll theme.
url: https://wlumme.github.io
baseurl: /concise
color:
  accent: green
  background: white
  foreground: black
  darkmode:
    background: black
    foreground: white
